project:
  type: website
  output-dir: docs

website:
  title: "Machine Learning to Kingdom Learning (ML2KL)"
  navbar:
    left:
      - href: index.qmd
        text: About
      - href: blog.qmd
        text: Motivation to Project
      - href: goals.qmd
        text: Project Goals and Contribution to SDGs
      - href: outcome.qmd
        text: Results Already Achieved 



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

